"""Entity store: stable identity for politicians, ministers, bureaucrats.

The entity record holds **only what's needed to identify a person**:
canonical name, alt-names, a stable id, and a primary kind. No biography,
no externally-sourced data. Every future enrichment (cabinet portfolio
history, ECI nominations, asset declarations, criminal records, DoPT
postings) is a **sidecar JSONL file** that joins on ``entity_id``.

Schema commitments (see ``entities/README.md`` written by ``save()``):

* ``people.jsonl`` — minimal identity records, schema-stable forever.
* ``mp_memberships.jsonl`` — temporal MP role data (one row per
  (entity_id, house, term)).
* ``committee_memberships.jsonl`` — temporal committee role data.
* ``ministerial_appointments.jsonl`` — temporal cabinet/MoS role data.
* ``bureaucratic_postings.jsonl`` — temporal IAS/civil-service role
  data, populated organically as bureaucrats are encountered in PDFs.

Reserved file names (schema committed, no implementation yet):

* ``eci_nominations.jsonl`` — Election Commission nomination records.
* ``asset_declarations.jsonl`` — wealth disclosures from nominations.
* ``criminal_records.jsonl`` — pending cases from nominations.
* ``bureaucratic_external.jsonl`` — DoPT cadre/batch/posting data.
* ``education.jsonl``, ``prior_career.jsonl`` — biographical sidecars.

The reserved-namespace policy means a future contributor knows the
file name in advance; nothing is named ad-hoc.

An optional external-priors layer (when activated) lives outside the
corpus directory. Entity records are the public identity layer; any
qualitative priors are kept separate.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Iterable

# ----------------------------------------------------------------------
# README written next to entities/ on save. Embedded here so the schema
# documentation versions with the code, not separately.
# ----------------------------------------------------------------------

_ENTITIES_README = """# entities/

Stable identity for politicians, ministers, bureaucrats, and (future)
external witnesses. Generated by ``sansad_semantic_crawler``; do not
hand-edit.

## Files

| File | What | When written |
|---|---|---|
| `people.jsonl` | Minimal identity records. Schema-stable forever. | Every crawl |
| `mp_memberships.jsonl` | Temporal MP role data. One row per (entity, house, term). | Every crawl |
| `committee_memberships.jsonl` | Temporal committee role data. | When committee composition is crawled |
| `ministerial_appointments.jsonl` | Temporal cabinet/MoS role data. | Populated when ministers are encountered as responders |
| `bureaucratic_postings.jsonl` | Temporal IAS/civil-service role data. | Populated organically from PDFs |

## Reserved (schema committed, not yet implemented)

| File | Will hold |
|---|---|
| `eci_nominations.jsonl` | Election Commission nomination records |
| `asset_declarations.jsonl` | Wealth disclosures from nominations |
| `criminal_records.jsonl` | Pending cases from nominations |
| `bureaucratic_external.jsonl` | DoPT cadre/batch/posting data |
| `education.jsonl` | Declared qualifications |
| `prior_career.jsonl` | Non-political career |

A future contributor knows the file name in advance; nothing should be
named ad-hoc.

## Schema rules

1. **Identity is schema-stable.** `people.jsonl` records keep their
   field set forever. Adding a field to that file is a breaking change.
   Add a sidecar instead.
2. **Sidecars join on `entity_id`.** Every other JSONL file in this
   directory has `entity_id` as its first field, referencing
   `people.jsonl`.
3. **Temporal records use `[start, end)` intervals.** `end: null` means
   the role is current/open. `start: null` means the start date is
   unknown.
4. **Records are append-only.** Re-running the crawler writes new rows
   for new observations; existing rows are preserved unchanged. The
   weighting engine and consumers can rely on stability.

## entity_id format

`PERSON_<8-hex>_<slug>` — deterministic from canonical_name + initial
context (house + party for MPs; ministry + designation for
bureaucrats). Re-running the scaffolding produces identical IDs for
the same person.

## Privacy

Public outputs. The optional external-priors layer (when activated)
lives outside the corpus directory. The ``weighting`` engine merges
priors into numeric weights but never copies raw text into corpus output.
"""

_HONORIFIC_RE = re.compile(
    r"\b(Shri|Smt|Dr|Prof|Babu|Ven'ble|Kumari|Sushri|Sardar|Adv|Hon'ble|Mr|Mrs|Ms)\b\.?\s*",
    re.IGNORECASE,
)


def normalize_name(name: str) -> str:
    """Stable canonical form for matching.

    1. Comma-reversal: 'Joshi, Shri P.V.' -> 'Shri P.V. Joshi'.
    2. Strip honorifics (Shri, Smt, Dr, ...).
    3. Lowercase, drop punctuation, collapse whitespace.
    4. Sort tokens alphabetically — order-independent canonical form,
       so 'P V Joshi' and 'Joshi P V' collapse to the same key.
    """
    if not name:
        return ""
    s = name
    if "," in s:
        parts = [p.strip() for p in s.split(",", 1)]
        if len(parts) == 2:
            s = f"{parts[1]} {parts[0]}"
    s = _HONORIFIC_RE.sub("", s)
    s = s.lower().replace(".", " ")
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    words = sorted(w for w in s.split() if w)
    return " ".join(words)


def slugify(name: str) -> str:
    """URL-safe slug for entity_id suffix. Word order preserved (not sorted)."""
    s = name.lower().replace(".", " ")
    s = _HONORIFIC_RE.sub("", s)
    s = re.sub(r"[^a-z0-9\s]", " ", s)
    return "_".join(w for w in s.split() if w)


def make_entity_id(canonical_name: str, *context: str) -> str:
    """Deterministic id from canonical_name + initial context.

    Context elements are stringified and joined; order matters so callers
    must use a stable order (e.g., always (house, party) for MPs).

    The hash is 8 hex chars, which is enough for ~4B entities before
    collision becomes a concern (we have ~thousands).
    """
    seed = "|".join([canonical_name.strip().lower()] + [str(c).strip().lower() for c in context])
    h = hashlib.sha256(seed.encode("utf-8")).hexdigest()[:8]
    return f"PERSON_{h}_{slugify(canonical_name)}"


def _now() -> str:
    return datetime.now().isoformat(timespec="seconds")


@dataclass
class Person:
    entity_id: str
    canonical_name: str
    alt_names: list[str] = field(default_factory=list)
    primary_kind: str = "politician"  # politician | bureaucrat | expert_witness | unknown
    first_seen_at: str = field(default_factory=_now)
    last_updated_at: str = field(default_factory=_now)


@dataclass
class MpMembership:
    entity_id: str
    house: str  # 'ls' | 'rs'
    term: int | None = None  # Lok Sabha number (17, 18, ...) or RS-term (when known)
    party: str = ""
    party_name: str = ""
    state: str | None = None
    constituency: str | None = None
    start: str | None = None  # ISO date
    end: str | None = None  # ISO date; null = currently sitting
    fetched_at: str = field(default_factory=_now)


@dataclass
class MinisterialAppointment:
    entity_id: str
    ministry: str
    rank: str  # 'cabinet' | 'mos_independent' | 'mos'
    start: str | None = None
    end: str | None = None
    govt_period: str | None = None  # 'Modi-2', 'UPA-1', etc.
    fetched_at: str = field(default_factory=_now)


@dataclass
class CommitteeMembership:
    entity_id: str
    committee_slug: str
    house: str
    role: str = "member"  # 'chairperson' | 'member'
    term: int | None = None
    start: str | None = None
    end: str | None = None
    fetched_at: str = field(default_factory=_now)


@dataclass
class BureaucraticPosting:
    entity_id: str
    designation: str
    ministry: str
    department: str | None = None
    cadre: str | None = None  # 'UP', 'TN', etc. (known only when stated)
    batch: int | None = None  # IAS batch year, when known
    start: str | None = None
    end: str | None = None
    fetched_at: str = field(default_factory=_now)


# Public file names — schema-committed, declared in README.
_PEOPLE = "people.jsonl"
_MP_MEMBERSHIPS = "mp_memberships.jsonl"
_MINISTERIAL = "ministerial_appointments.jsonl"
_COMMITTEE = "committee_memberships.jsonl"
_BUREAU_POSTINGS = "bureaucratic_postings.jsonl"


class EntityStore:
    """Persistent, append-only entity store.

    Lives under ``<out_dir>/entities/``. Append-only on disk; in-memory
    indexes (by entity_id, by normalized name) are rebuilt on load.
    """

    def __init__(self, out_dir: Path):
        self.out_dir = out_dir
        self.dir = out_dir / "entities"
        self.people: dict[str, Person] = {}
        # normalized_name -> set of entity_ids (multi-valued; same name can map
        # to several entities when context disambiguates)
        self._by_norm: dict[str, set[str]] = {}
        self.mp_memberships: list[MpMembership] = []
        self.committee_memberships: list[CommitteeMembership] = []
        self.ministerial_appointments: list[MinisterialAppointment] = []
        self.bureaucratic_postings: list[BureaucraticPosting] = []

    # ---- I/O ----

    def load(self) -> None:
        """Rebuild in-memory state from disk. No-op if the dir is empty."""
        if not self.dir.exists():
            return
        people_path = self.dir / _PEOPLE
        if people_path.exists():
            for line in people_path.read_text(encoding="utf-8").splitlines():
                if not line.strip():
                    continue
                row = json.loads(line)
                p = Person(**row)
                self.people[p.entity_id] = p
                self._index_name(p)
        for path, target_cls, target_list in [
            (self.dir / _MP_MEMBERSHIPS, MpMembership, self.mp_memberships),
            (self.dir / _COMMITTEE, CommitteeMembership, self.committee_memberships),
            (self.dir / _MINISTERIAL, MinisterialAppointment, self.ministerial_appointments),
            (self.dir / _BUREAU_POSTINGS, BureaucraticPosting, self.bureaucratic_postings),
        ]:
            if path.exists():
                for line in path.read_text(encoding="utf-8").splitlines():
                    if line.strip():
                        target_list.append(target_cls(**json.loads(line)))

    def save(self) -> None:
        """Write current state to disk. Overwrites; callers stage all changes
        in-memory then call save() once."""
        self.dir.mkdir(parents=True, exist_ok=True)
        (self.dir / "README.md").write_text(_ENTITIES_README, encoding="utf-8")
        with (self.dir / _PEOPLE).open("w", encoding="utf-8") as f:
            for p in self.people.values():
                f.write(json.dumps(asdict(p), ensure_ascii=False, sort_keys=True) + "\n")
        for fname, items in [
            (_MP_MEMBERSHIPS, self.mp_memberships),
            (_COMMITTEE, self.committee_memberships),
            (_MINISTERIAL, self.ministerial_appointments),
            (_BUREAU_POSTINGS, self.bureaucratic_postings),
        ]:
            with (self.dir / fname).open("w", encoding="utf-8") as f:
                for row in items:
                    f.write(json.dumps(asdict(row), ensure_ascii=False, sort_keys=True) + "\n")

    # ---- Mutators ----

    def add_person(self, person: Person) -> Person:
        """Idempotent insert. If entity_id already known, merge alt_names."""
        existing = self.people.get(person.entity_id)
        if existing is None:
            self.people[person.entity_id] = person
            self._index_name(person)
            return person
        # Merge alt_names; keep first_seen_at; update last_updated_at.
        merged_alt = sorted(set(existing.alt_names) | set(person.alt_names) | {person.canonical_name} - {existing.canonical_name})
        existing.alt_names = [a for a in merged_alt if a and a != existing.canonical_name]
        existing.last_updated_at = _now()
        self._index_name(existing)
        return existing

    def add_mp_membership(self, m: MpMembership) -> None:
        # Dedup on (entity_id, house, term, party).
        key = (m.entity_id, m.house, m.term, m.party)
        for existing in self.mp_memberships:
            if (existing.entity_id, existing.house, existing.term, existing.party) == key:
                return
        self.mp_memberships.append(m)

    def add_committee_membership(self, m: CommitteeMembership) -> None:
        key = (m.entity_id, m.committee_slug, m.term, m.role)
        for existing in self.committee_memberships:
            if (existing.entity_id, existing.committee_slug, existing.term, existing.role) == key:
                return
        self.committee_memberships.append(m)

    def add_ministerial_appointment(self, m: MinisterialAppointment) -> None:
        key = (m.entity_id, m.ministry, m.rank, m.start)
        for existing in self.ministerial_appointments:
            if (existing.entity_id, existing.ministry, existing.rank, existing.start) == key:
                return
        self.ministerial_appointments.append(m)

    def add_bureaucratic_posting(self, p: BureaucraticPosting) -> None:
        key = (p.entity_id, p.designation, p.ministry, p.start)
        for existing in self.bureaucratic_postings:
            if (existing.entity_id, existing.designation, existing.ministry, existing.start) == key:
                return
        self.bureaucratic_postings.append(p)

    # ---- Queries ----

    def find_by_id(self, entity_id: str) -> Person | None:
        return self.people.get(entity_id)

    def find_by_name(self, name: str) -> list[Person]:
        """Return all people whose canonical or alt name matches the
        normalized form of ``name``. Empty list if no match."""
        if not name:
            return []
        norm = normalize_name(name)
        ids = self._by_norm.get(norm, set())
        return [self.people[eid] for eid in ids if eid in self.people]

    def memberships_for(self, entity_id: str) -> Iterable[MpMembership]:
        return [m for m in self.mp_memberships if m.entity_id == entity_id]

    def ministerial_for(self, entity_id: str) -> Iterable[MinisterialAppointment]:
        return [m for m in self.ministerial_appointments if m.entity_id == entity_id]

    # ---- Internal ----

    def _index_name(self, person: Person) -> None:
        for nm in [person.canonical_name, *person.alt_names]:
            norm = normalize_name(nm)
            if norm:
                self._by_norm.setdefault(norm, set()).add(person.entity_id)


# ----------------------------------------------------------------------
# Adapters: translate other in-memory data sources into entity rows.
# Duck-typed; no imports of the source modules to avoid circular deps.
# ----------------------------------------------------------------------


def _house_short(house_long: str | None) -> str:
    """Map sansad.in's house labels ('Lok Sabha' / 'Rajya Sabha') to short form."""
    if not house_long:
        return ""
    h = house_long.lower()
    if h.startswith("lok"):
        return "ls"
    if h.startswith("raj"):
        return "rs"
    return h


def populate_entity_store_from_mp_roster(
    roster, store: EntityStore, *, ls_term: int = 18
) -> tuple[int, int]:
    """Translate an ``MPRoster``'s in-memory members into entity records.

    Returns ``(people_added, memberships_added)`` for telemetry. Idempotent:
    re-running with the same roster is a no-op.

    The roster is duck-typed via ``iter_members()`` so this function does not
    import ``MPRoster`` directly. Tests can pass in any object with a
    compatible iterator yielding objects with ``name``, ``party``,
    ``party_name``, ``state``, ``house`` attributes.

    LS members are stamped with ``term=ls_term`` (default 18). RS members
    leave ``term=None`` because RS does not have term numbers; individual
    elected terms are tracked in ``start``/``end`` when known.
    """
    people_before = len(store.people)
    memberships_before = len(store.mp_memberships)

    for info in roster.iter_members():
        name = (info.name or "").strip()
        if not name:
            continue
        party = (info.party or "").strip()
        party_name = (info.party_name or "").strip()
        state = (info.state or None)
        house = _house_short(info.house)

        # entity_id seed: canonical_name + house + party. Stable across reruns.
        eid = make_entity_id(name, house, party)
        store.add_person(
            Person(
                entity_id=eid,
                canonical_name=name,
                primary_kind="politician",
            )
        )
        store.add_mp_membership(
            MpMembership(
                entity_id=eid,
                house=house,
                term=(ls_term if house == "ls" else None),
                party=party,
                party_name=party_name,
                state=state,
            )
        )

    return (
        len(store.people) - people_before,
        len(store.mp_memberships) - memberships_before,
    )
